model_params:
  model_type: "KAN_FAST"  # KAN_FAST, resnet50, diatnet, vgg16, densenet121, mobilenet_v2, efficientnet_b0, vit_b_16
  num_classes: 12
  optimizer: "adam"
  learning_rate: 1e-4
  max_epochs: 20
  scheduler:
    factor: 0.5
    patience: 3
    min_lr: 1e-7
    monitor: "val_loss"
    mode: "min"
    threshold: 1e-4
    cooldown: 0

data_params:
  dataset_name: "spect_data" 
  train_dir: "data/${data_params.dataset_name}/train"
  val_dir: "data/${data_params.dataset_name}/val"
  test_dir: "data/${data_params.dataset_name}/test"
  batch_size: 32
  num_workers: 8
  precision: "16-mixed"
  gradient_accumulation_steps: 2
  val_split: 0.2  
  seed: 42  

log_params:
  models_dir: "models"
  checkpoint_name: "${model_params.model_type}_${data_params.dataset_name}"

test_params:
  checkpoint_path: "logs/models/${log_params.checkpoint_name}.ckpt"  

hydra:
  run:
    dir: logs/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/hydra/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job_logging:
    version: 1
    root:
      handlers: [stream]
    formatters:
      simple:
        format: '%(name)s %(levelname)s: %(message)s'
    handlers:
      stream:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    loggers:
      lightning:
        level: INFO