model_params:
  model_name: "KAN"
  model_type: "NORMAL"
  num_classes: 4
  optimizer: "adamw"
  learning_rate: 1e-4
  max_epochs: 10

data_params:
  train_dir: "data/train"
  val_dir: "data/val"
  test_dir: "data/test"
  batch_size: 32
  num_workers: 8
  precision: "16-mixed"
  gradient_accumulation_steps: 2

log_params:
  models_dir: "models"


hydra:
  run:
    dir: logs/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job_logging:
    version: 1
    root:
      handlers: [stream]
    formatters:
      simple:
        format: '%(name)s %(levelname)s: %(message)s'
    handlers:
      stream:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    loggers:
      lightning:
        level: INFO


